### ISSUE TITLE
Include init containers

### ISSUE THREAD

**Issue by davidreuss** [boz/kail#14]
Would it be possible to include init-containers in output?

**Comment by boz** [comment]
Great idea.  If [Read Log](https://kubernetes.io/docs/api-reference/v1.8/#read-log) works for init-containers then yeah, it should be doable.

I don't have time at the moment to get to it, but will try to get to it at some point.

If anyone else wants to tackle the issue, it will probably take something like

1. include init containers by looking at `InitContainerStatuses` [here](https://github.com/boz/kail/blob/master/filter.go#L39)
1. figure out reasonable behavior for when to display init container logs and when to [stop monitoring them](https://github.com/boz/kail/blob/master/controller.go#L195).

**Comment by davidreuss** [comment]
was just reading the source, and yes it might just be adding initContainers in the filter at:

https://github.com/boz/kail/blob/dab2d1ed7a33b2afba4a0c495cfe5248ec701a7f/filter.go#L35

I don't have time until next week, but if i get it working i'll do a PR for it.

Thanks for the pointers as well.

**Comment by davidreuss** [comment]
So, #15 seems to work in my local testing .. regarding when to stop monitoring them, if i understand the code correctly, then cleanup should already happen, as finished init containers will not be considered from the filter (they're not running anymore), and thus will be automatically prune from the sources.

```
	if pms, ok := c.monitors[id]; ok {
		for source, pm := range pms {
			if !sources[source] {
				pm.Shutdown()
			}
		}
	}
```

Is that understood correctly?

From the debug logs in my testing example it looks like it at least where i get

```
DEBU[0025] removing source prod/api-7805699-0mpq0@init   cmp=kail.controller
```

**Comment by boz** [comment]
@davidreuss: yep, that's right.
