### ISSUE TITLE
Cannot use kail on Windows/Git Bash -- cannot open `/dev/stderr`

### ISSUE THREAD

**Issue by fbiville** [boz/kail#23]
Here is what happens:

```
$ kail --help
kail.exe: error: open /dev/stderr: The system cannot find the path specified., try --help
```

**Comment by fbiville** [comment]
Maybe it boils down to a permission issue?
```
IEUser@MSEDGEWIN10 MINGW64 ~/workspace/fats (issue_46)
$ kail --help
kail.exe: error: open /dev/stderr: The system cannot find the path specified., try --help

IEUser@MSEDGEWIN10 MINGW64 ~/workspace/fats (issue_46)
$ ls -lisa /dev/stderr
562949953534840 1 lrwxrwxrwx 1 IEUser 197121 15 Oct 17 08:02 /dev/stderr -> /proc/self/fd/2

IEUser@MSEDGEWIN10 MINGW64 ~/workspace/fats (issue_46)
$ ls -lisa /proc/self/fd/2
15871480675977711661 0 lrwxrwxrwx 1 IEUser 197121 0 Oct 17 09:01 /proc/self/fd/2 -> /dev/pty0

IEUser@MSEDGEWIN10 MINGW64 ~/workspace/fats (issue_46)
$ ls -lisa /dev/pty0
8912896 0 crw------- 1 IEUser 197121 136, 0 Oct 17 09:02 /dev/pty0
```

**Comment by fbiville** [comment]
Or rather, kail does not follow symlink when opening `/dev/stderr`?

**Comment by boz** [comment]
Thanks @fbiville.  I'm not sure why your workaround doesn't work.   Maybe just create a `/dev` directory?

You can also try specifying a different log file with `--log-file <path>`.  

It's opening `/dev/stderr` for logging as a convenience, maybe that just won't work on Windows.  The relevant code is [here](https://github.com/boz/kail/blob/62372338c90a53d48566a637c5afbed4c9926452/cmd/kail/main.go#L55-L57).

What is `os.Stderr.Name()` on your system?  I wonder if it's a different path or if the open flags won't work on Windows.

**Comment by fbiville** [comment]
@boz actually, this whole setup is a standard Git Bash install (used by Travis CI as well on [Windows workers](https://blog.travis-ci.com/2018-10-11-windows-early-release)). I'll come back to you ASAP with the value `os.Stderr.Name()`

**Comment by fbiville** [comment]
Just ran it, it returns `/dev/stderr` in Git Bash, cmd and Powershell.

**Comment by scothis** [comment]
I've been able to work around this issue by redirecting stderr to stdout `2>&1`. There's something a bit different with git bash on Windows.

**Comment by k1ng440** [comment]
does not work on PowerShell either
