### ISSUE TITLE
Feature: Parse JSON logs

### ISSUE THREAD

**Issue by esiqveland** [boz/kail#31]
It would be very nice if kail could parse each line as a json document, then only print some selection of fields.

Most of our services print json documents on console, which is recorded then shipped to ES.

I could be willing to work on this, but some pointers on how it should be done would be nice.

**Comment by chandanpasunoori** [comment]
@esiqveland  json parsing is added you, instead of adding json field selections you can use jq  

```bash
$ kail -o json|jq '.name'
```
