### ISSUE TITLE
Make a plugin: kubectl tail

### ISSUE THREAD

**Issue by ahmetb** [boz/kail#34]
👋 Hello, maintainer of the kubectl plugin manager **krew** here (https://github.com/kubernetes-sigs/krew).

What do you think of distributing this as a kubectl plugin named `kubectl tail`? 

Why?

- kubectl plugins are becoming a thing now, we have over 30 plugins.
- `kubectl tail` is more natural and memorable than a custom binary name
- krew helps you package/distribute your tool on macOS, Linux and Windows so you don't deal with homebrew, apt/dnf, chocolatey etc separately.

I suspect there would be no code changes required. The release process would involve periodic updates to the plugin manifest file hosted at https://github.com/kubernetes-sigs/krew-index/tree/master/plugins.

**Comment by boz** [comment]
Hi @ahmetb, thanks for reaching out.

Yes, that sounds great!  Do plugins have to adhere to any standards such as argument parsing, etc...?

Is there anything I need to do other than to make a PR for the manifest file?

**Comment by ahmetb** [comment]
We only enforce naming guidelines in krew-index repo. 
Ideally you should use the `k8s.io/cli-runtime/pkg/genericclioptions` for the flags like -n/-namespace, but it’s optional. 

Give it a try sometime. We have a developer guide in krew repository.

**Comment by boz** [comment]
fixed in kubernetes-sigs/krew-index#150

**Comment by ahmetb** [comment]
You can also document installation as a plugin if you’d like.  

1. Install krew
2. kubectl krew install tail
