### ISSUE TITLE
In v0.10.1 release please fix checksums.txt file name

### ISSUE THREAD

**Issue by vshalchian** [boz/kail#37]
Please rename checksums.txt to kail_0.10.1_checksums.txt

The install script will fail because it looks for a different file name

/tmp/install_kail -d
boz/kail info checking GitHub for latest tag
boz/kail debug http_download https://github.com/boz/kail/releases/latest
boz/kail info found version: 0.10.1 for v0.10.1/linux/amd64
boz/kail debug downloading files into /tmp/tmp.fhR7MdVmab
boz/kail debug http_download https://github.com/boz/kail/releases/download/v0.10.1/kail_0.10.1_linux_amd64.tar.gz
boz/kail debug http_download https://github.com/boz/kail/releases/download/v0.10.1/kail_0.10.1_checksums.txt
boz/kail debug http_download_curl received HTTP status 404

**Comment by boz** [comment]
Thanks, will do.

**Comment by vshalchian** [comment]
Is there any ETA for that ?

Thanks
