### ISSUE TITLE
Release? DNS on macOS with VPNs doesn't work

### ISSUE THREAD

**Issue by rcoup** [boz/kail#60]
When connected to a VPN on macOS which is used for DNS-lookups:

```console
$ kail -d my-deploy
kail: error: Can't connnect to kubernetes: Get https://api.my.k8s.example.com/api/v1/namespaces:
dial tcp: lookup api.my.k8s.example.com on 192.168.1.254:53: no such host
```

It's basically a Go issue where it [doesn't check the places it needs to for DNS resolution on macOS](https://docwhat.org/macos-dns-and-go). But it's fixed in Go 1.13, which is already used for kail on master 🥳 

Possible to cut a release?

**Comment by chandanpasunoori** [comment]
its fixed in newer releases
