### ISSUE TITLE
Homebrew: Calling `bottle :unneeded` is deprecated

### ISSUE THREAD

**Issue by rblaine95** [boz/kail#66]
Hi there

I ran a `brew upgrade` today and got this warning:
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the boz/repo tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/boz/homebrew-repo/kail.rb:6
```

**Comment by RomansWorks** [comment]
Not a maintainer but this looks like the result of https://github.com/goreleaser/goreleaser/pull/2591.

So one needs to generate the ruby files using goreleaser in this repo and open a PR / push to https://github.com/boz/homebrew-repo

**Comment by boz** [comment]
Hey there, thanks for reporting this!  Sorry for the delay.

**Comment by bizrad** [comment]
@boz looks like you can close this issue
