### ISSUE TITLE
Become a Krew extension

### ISSUE THREAD

**Issue by jglick** [boz/kail#67]
So people could just

```bash
kubectl krew install kail
kubectl kail
```

rather than figuring out https://github.com/boz/kail#downloading

**Comment by totoroot** [comment]
@jglick It can already be installed with `kubectl krew install tail`.
For whatever reason it is just not in the README.
For more information see related issue https://github.com/boz/kail/issues/34

Pinging @bizrad @rblaine95. Since you liked this issue, I suppose you did not know this as well.

**Comment by rblaine95** [comment]
Very nice, didn't realize that! Thank you @totoroot 

Now just need to wait for a release for `darwin/arm64`
```
» k krew install tail
Updated the local copy of plugin index.
Installing plugin: tail
W0209 13:39:56.885669   19352 install.go:164] failed to install plugin "tail": plugin "tail" does not offer installation for this platform
failed to install some plugins: [tail]: plugin "tail" does not offer installation for this platform
```

**Comment by jglick** [comment]
Installed, and `kubectl tail` working. Thanks!
