### ISSUE TITLE
arm64 support in krew

### ISSUE THREAD

**Issue by chandanpasunoori** [boz/kail#68]
krew installation failing for arm64 and I don't see arm64 in https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/tail.yaml or https://github.com/boz/kail/releases 

can we add this, I can see https://github.com/boz/kail/blob/master/.goreleaser.yml already has arm64. 

what is required to add arm64 in release, I can contribute if you require.

```
$ kubectl krew version
```
```
OPTION            VALUE
GitTag            v0.4.3
GitCommit         dbfefa5
IndexURI          https://github.com/kubernetes-sigs/krew-index.git
BasePath          /Users/cp/.krew
IndexPath         /Users/cp/.krew/index/default
InstallPath       /Users/cp/.krew/store
BinPath           /Users/cp/.krew/bin
DetectedPlatform  darwin/arm64
```
```
$ kubectl krew install tail
```
Updated the local copy of plugin index.
Installing plugin: tail
W0317 15:01:20.772855   61973 install.go:164] failed to install plugin "tail": plugin "tail" does not offer installation for this platform
failed to install some plugins: [tail]: plugin "tail" does not offer installation for this platform
```

**Comment by boz** [comment]
Thanks @chandanpasunoori - I'll update the build process ASAP.

**Comment by chandanpasunoori** [comment]
hi @boz any update on this?

**Comment by boz** [comment]
Updating the deps and modernizing the build tools is a bit of a quagmire, unfortunately.

Will continue chipping away at it.

**Comment by mnaser** [comment]
@boz I went ahead and took care of this:

https://github.com/boz/kail/pull/72

It does require a bump in one of your other dependencies but that's taken care of.  Once that lands, we can probably close all those krew related issues :)

**Comment by chandanpasunoori** [comment]
hi @boz @mnaser any update on this?

**Comment by chandanpasunoori** [comment]
arm64 support in krew working

$ kubectl krew install tail
Updated the local copy of plugin index.
Installing plugin: tail
Installed plugin: tail
\
 | Use this plugin:
 | 	kubectl tail
 | Documentation:
 | 	https://github.com/boz/kail
/
WARNING: You installed plugin "tail" from the krew-index plugin repository.
   These plugins are not audited for security by the Krew maintainers.
   Run them at your own risk.

$ kubectl krew info tail
NAME: tail
INDEX: default
URI: https://github.com/boz/kail/releases/download/v0.16.1/kail_v0.16.1_darwin_arm64.tar.gz
SHA256: 53bd81efe1c85d51d3688d7b0575fba458d75954895ca50d211ff31e5ca9f5a0
VERSION: v0.16.1
HOMEPAGE: https://github.com/boz/kail
DESCRIPTION:
Kail https://github.com/boz/kail - "Just show me the logs"

Stream logs from all matched containers of all matched pods.  Match pods by service,
replicaset, deployment, and others.  Adjusts to a changing cluster - pods are
added and removed from logging as they fall in or out of the selection.

Documentation:

  See https://github.com/boz/kail or

  $ kubectl tail --help

Usage:

  # match all pods
  $ kubectl tail

  # match pods in the 'frontend' namespace
  $ kubectl tail --ns staging

  # match pods belonging to a replicaset named 'workers' in any namespace.
  $ kubectl tail --rs workers

  # match pods belonging to the replicaset named 'workers' only in the 'staging' namespace
  $ kubectl tail --rs staging/workers

  # match pods belonging to both the service "frontend" and the deployment "webapp"
  $ kubectl tail --svc frontend --deploy webapp


$ kubectl tail version
v0.16.1 (625673f)
