### ISSUE TITLE
Plans for a Windows binary?

### ISSUE THREAD

**Issue by alexellis** [boz/kail#71]
Hi,

I was recommending kail for openfaas users, but whilst trying to help a Windows user today, I realised they couldn't use this tool.

Would you consider shipping a Windows binary for kail? If so, do you need any help with this?

Alex

**Comment by alexellis** [comment]
Thanks @mnaser 

@Jasstkn would you like to update arkade for the above?

**Comment by Jasstkn** [comment]
@mnaser hey. [I don't see any os assets](https://github.com/boz/kail/releases/tag/v0.17.0) in the latest release. Can you please double-check if something is wrong in the release pipeline?

**Comment by Slach** [comment]
@Jasstkn look https://github.com/boz/kail/pull/142

need wait next release

**Comment by Jasstkn** [comment]
> @Jasstkn look #142
> 
> need wait next release

gotcha, thanks!

**Comment by Slach** [comment]
@alexellis no, wait next release after mantainers will merge https://github.com/boz/kail/pull/146

**Comment by mnaser** [comment]
merged and a new release is out. :)

**Comment by Jasstkn** [comment]
> Thanks @mnaser
> 
> @Jasstkn would you like to update arkade for the above?

no changes to support Windows are required in the arkade. ✅
