### ISSUE TITLE
missing example of ignore

### ISSUE THREAD

**Issue by MushiTheMoshi** [boz/kail#75]
Hi there,

First of all, thanks for all the work done here, very handy tool, really like it, using it all the time. 

Can you please provide an example on how to use ignore, I want to ignore certain pods and could not find a way on how to do it.

Thanks in advanced,
Julio

**Comment by chandanpasunoori** [comment]
@MushiTheMoshi 

use can use 2 ways 

> with --ignore-ns (ignoring namespace)
> this is useful when you have deployments with same name in multiple namespaces

`kail --context=c1 -d nec --ignore-ns=n1 --since=1h`

> with --ignore (ignoring deployment from namespace)
> this is useful when you have multiple deployments in same namespace, and tailing all logs from name space except few deployments 

`kail --context=c1 -n n1 --ignore=app=a1 --ignore=app=b1 --since=1h`

this applies for all other types of workloads too
